#!/usr/bin/env python3
"""
Generate DOM glass sphere geometry for END.geo.

Reads the existing PMTINFO.ratdb to find DOM centers (every 31 PMTs),
then generates:
  1. Glass sphere shell entries (borosilicate glass, 17" VITROVEX)
  2. Water-filled interior sphere entries (PMT mother volumes)
  3. Per-DOM pmtarray entries replacing the single km3net_doms entry

VITROVEX 17-inch sphere specs (KM3NeT):
  - Outer diameter: 432 mm (17 inch) -> outer radius = 216.0 mm
  - Wall thickness: 14 mm
  - Inner radius: 202.0 mm
  - Material: 3.3 Borosilicate glass (Schott DURAN / VITROVEX)

PMTs (R12199) sit at ~198 mm from DOM center, so ~4 mm clearance
from the inner glass surface.
"""

import re
import math
from scipy.optimize import minimize

PMTINFO_FILE = "ratdb/End/PMTINFO.ratdb"
OUTPUT_FILE = "ratdb/End/END_dom.geo"

PMTS_PER_DOM = 31
OUTER_RADIUS = 216.0  # mm, 17-inch / 2
WALL_THICKNESS = 13.0  # mm (nominal 14mm, reduced to 13mm for PMT face clearance)
INNER_RADIUS = OUTER_RADIUS - WALL_THICKNESS  # 203.0 mm


def read_pmtinfo(path, table_name="DOMINFO_aframe_spacing5m_hex_v3"):
    with open(path, "r") as f:
        content = f.read()
    # Find the specific table by name
    tables = content.split("{")
    for t in tables:
        if table_name in t:
            full_table = "{" + t
            x = [float(v) for v in re.search(r"x:\[([^\]]+)\]", full_table).group(1).split(",")]
            y = [float(v) for v in re.search(r"y:\[([^\]]+)\]", full_table).group(1).split(",")]
            z = [float(v) for v in re.search(r"z:\[([^\]]+)\]", full_table).group(1).split(",")]
            return x, y, z
    raise ValueError(f"Table '{table_name}' not found in {path}")


def fit_sphere_center(px, py, pz):
    """Fit a sphere center to a set of points."""
    cx0 = sum(px) / len(px)
    cy0 = sum(py) / len(py)
    cz0 = sum(pz) / len(pz)

    def err(params):
        cx, cy, cz = params
        ds = [
            math.sqrt((px[i] - cx) ** 2 + (py[i] - cy) ** 2 + (pz[i] - cz) ** 2)
            for i in range(len(px))
        ]
        m = sum(ds) / len(ds)
        return sum((d - m) ** 2 for d in ds)

    result = minimize(err, [cx0, cy0, cz0], method="Nelder-Mead")
    return result.x


def generate_geo():
    x, y, z = read_pmtinfo(PMTINFO_FILE)
    n_doms = len(x) // PMTS_PER_DOM
    assert len(x) == n_doms * PMTS_PER_DOM, (
        f"PMT count {len(x)} not divisible by {PMTS_PER_DOM}"
    )

    print(f"Total PMTs: {len(x)}, DOMs: {n_doms}")

    lines = []
    lines.append("// AUTO-GENERATED by generate_dom_geometry.py")
    lines.append("// VITROVEX 17-inch borosilicate glass DOMs for KM3NeT-style detector")
    lines.append(f"// {n_doms} DOMs, {PMTS_PER_DOM} PMTs each")
    lines.append(f"// Glass: outer R = {OUTER_RADIUS} mm, wall = {WALL_THICKNESS} mm, inner R = {INNER_RADIUS} mm")
    lines.append("")

    dom_centers = []

    for dom_idx in range(n_doms):
        start = dom_idx * PMTS_PER_DOM
        end = start + PMTS_PER_DOM
        px = x[start:end]
        py = y[start:end]
        pz = z[start:end]

        cx, cy, cz = fit_sphere_center(px, py, pz)
        dom_centers.append((cx, cy, cz))

        # Verify PMTs fit inside the inner radius
        max_dist = max(
            math.sqrt((px[i] - cx) ** 2 + (py[i] - cy) ** 2 + (pz[i] - cz) ** 2)
            for i in range(PMTS_PER_DOM)
        )
        if max_dist > INNER_RADIUS:
            print(
                f"  WARNING: DOM {dom_idx} max PMT distance {max_dist:.1f} > inner radius {INNER_RADIUS}"
            )

        # Glass sphere (full solid sphere of glass, placed in detector)
        # The water interior is a daughter of this glass sphere.
        # This avoids overlap: glass is the outer shell, water fills the inside.
        lines.append("{")
        lines.append(f'name: "GEO",')
        lines.append(f'index: "dom_glass_{dom_idx}",')
        lines.append(f"valid_begin: [0, 0],")
        lines.append(f"valid_end: [0, 0],")
        lines.append(f'mother: "detector",')
        lines.append(f'type: "sphere",')
        lines.append(f"r_max: {OUTER_RADIUS},")
        lines.append(f"position: [{cx:.4f}, {cy:.4f}, {cz:.4f}],")
        lines.append(f'material: "borosilicate_glass",')
        lines.append(f"color: [0.8, 0.9, 1.0, 0.3],")
        lines.append(f'drawstyle: "wireframe"')
        lines.append("}")
        lines.append("")

        # Water-filled interior (daughter of glass sphere, PMT mother volume)
        # Position [0,0,0] since it's centered inside its glass mother
        lines.append("{")
        lines.append(f'name: "GEO",')
        lines.append(f'index: "dom_inner_{dom_idx}",')
        lines.append(f"valid_begin: [0, 0],")
        lines.append(f"valid_end: [0, 0],")
        lines.append(f'mother: "dom_glass_{dom_idx}",')
        lines.append(f'type: "sphere",')
        lines.append(f"r_max: {INNER_RADIUS},")
        lines.append(f"position: [0.0, 0.0, 0.0],")
        lines.append(f'material: "lake_water",')
        lines.append(f"color: [0.0, 0.5, 1.0, 0.1],")
        lines.append(f"invisible: 1,")
        lines.append(f'drawstyle: "wireframe"')
        lines.append("}")
        lines.append("")

    # Per-DOM pmtarray entries
    lines.append("////// PMT arrays — one per DOM //////")
    lines.append("")

    for dom_idx in range(n_doms):
        start_idx = dom_idx * PMTS_PER_DOM
        end_idx = start_idx + PMTS_PER_DOM - 1

        lines.append("{")
        lines.append(f'name: "GEO",')
        lines.append(f'index: "dom_pmts_{dom_idx}",')
        lines.append(f"valid_begin: [0, 0],")
        lines.append(f"valid_end: [0, 0],")
        lines.append(f'mother: "dom_inner_{dom_idx}",')
        lines.append(f'type: "pmtarray",')
        lines.append(f"start_idx: {start_idx},")
        lines.append(f"end_idx: {end_idx},")
        lines.append(f'pmt_model: "r12199",')
        lines.append(f"mu_metal: 0,")
        lines.append(f'mu_metal_material: "aluminum",')
        lines.append(f'mu_metal_surface: "aluminum",')
        lines.append(f"light_cone: 0,")
        lines.append(f'pmt_detector_type: "idpmt",')
        lines.append(f'sensitive_detector: "/mydet/pmt/inner",')
        lines.append(f"efficiency_correction: 0.70000,")
        lines.append(f'pos_table: "DOMINFO_aframe_spacing5m_hex_v3",')
        lines.append(f'orientation: "manual",')
        lines.append(f"invisible: 0,")
        lines.append(f"color: [1.0, 0.0, 1.0, 0.5],")
        lines.append(f'drawstyle: "wireframe"')
        lines.append("}")
        lines.append("")

    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(lines))

    print(f"Written {OUTPUT_FILE}")
    print(f"  {n_doms} glass shells (dom_glass_N)")
    print(f"  {n_doms} inner volumes (dom_inner_N)")
    print(f"  {n_doms} pmtarray entries (dom_pmts_N)")

    # Print summary of DOM positions
    print("\nDOM center positions (first 5 and last 3):")
    for i in range(min(5, n_doms)):
        cx, cy, cz = dom_centers[i]
        print(f"  DOM {i:3d}: ({cx:9.1f}, {cy:7.1f}, {cz:10.1f})")
    if n_doms > 8:
        print("  ...")
    for i in range(max(5, n_doms - 3), n_doms):
        cx, cy, cz = dom_centers[i]
        print(f"  DOM {i:3d}: ({cx:9.1f}, {cy:7.1f}, {cz:10.1f})")


if __name__ == "__main__":
    generate_geo()
